/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as AreaClienteRouteImport } from './routes/area-cliente'
import { Route as AdminCajunaRouteImport } from './routes/admin-cajuna'
import { Route as IndexRouteImport } from './routes/index'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaClienteRoute = AreaClienteRouteImport.update({
  id: '/area-cliente',
  path: '/area-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCajunaRoute = AdminCajunaRouteImport.update({
  id: '/admin-cajuna',
  path: '/admin-cajuna',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-cajuna': typeof AdminCajunaRoute
  '/area-cliente': typeof AreaClienteRoute
  '/orcamento': typeof OrcamentoRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-cajuna': typeof AdminCajunaRoute
  '/area-cliente': typeof AreaClienteRoute
  '/orcamento': typeof OrcamentoRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-cajuna': typeof AdminCajunaRoute
  '/area-cliente': typeof AreaClienteRoute
  '/orcamento': typeof OrcamentoRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-cajuna'
    | '/area-cliente'
    | '/orcamento'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-cajuna' | '/area-cliente' | '/orcamento' | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/admin-cajuna'
    | '/area-cliente'
    | '/orcamento'
    | '/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCajunaRoute: typeof AdminCajunaRoute
  AreaClienteRoute: typeof AreaClienteRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PortfolioRoute: typeof PortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-cliente': {
      id: '/area-cliente'
      path: '/area-cliente'
      fullPath: '/area-cliente'
      preLoaderRoute: typeof AreaClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-cajuna': {
      id: '/admin-cajuna'
      path: '/admin-cajuna'
      fullPath: '/admin-cajuna'
      preLoaderRoute: typeof AdminCajunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCajunaRoute: AdminCajunaRoute,
  AreaClienteRoute: AreaClienteRoute,
  OrcamentoRoute: OrcamentoRoute,
  PortfolioRoute: PortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
